### ISSUE TITLE
Similar tag is repeated multiple times

### ISSUE THREAD

**Issue by RCheesley** [google/triage-party#196]
I noticed that the similar tag seems to be getting repeated for some of the PR's - not sure if it is a bug or by design!

![screenshot-127 0 0 1_8080-2020 07 30-14_29_36](https://user-images.githubusercontent.com/2930593/88928809-28733e00-d271-11ea-8d4b-e60674619143.png)

Currently on v1.2.1.

**Comment by MushuEE** [comment]
Looking at [minikube dashboard](https://teaparty-tts3vkcpgq-uc.a.run.app/s/daily-triage) seeing the same

![image](https://user-images.githubusercontent.com/7189267/90324437-bf075680-df23-11ea-86fe-5b3ff47b82f7.png)

Options for fixes:
1) Make the Tags a set `map[*Tag]bool` so that there are never dupe Tags.
2) Find the reason there are so many 'similar' tags
3) check if that tag already exists and do not re-append to Tags.
